apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: gcr.io/advert-proj/advert-pred-pipeline
  tagPolicy:
    envTemplate:
      template: latest
kind: Config
